theme: jekyll-theme-minimal
logo: /assets/academic_photo_portrait_small_2.jpeg
title: Simon's homepage
description: Asteroseismologist. Data Analyst. Purveyor of stellar ages.
google_analytics: UA-30960531-1
